//#region \0vite/modulepreload-polyfill.js
(function polyfill() {
	const relList = document.createElement("link").relList;
	if (relList && relList.supports && relList.supports("modulepreload")) return;
	for (const link of document.querySelectorAll("link[rel=\"modulepreload\"]")) processPreload(link);
	new MutationObserver((mutations) => {
		for (const mutation of mutations) {
			if (mutation.type !== "childList") continue;
			for (const node of mutation.addedNodes) if (node.tagName === "LINK" && node.rel === "modulepreload") processPreload(node);
		}
	}).observe(document, {
		childList: true,
		subtree: true
	});
	function getFetchOpts(link) {
		const fetchOpts = {};
		if (link.integrity) fetchOpts.integrity = link.integrity;
		if (link.referrerPolicy) fetchOpts.referrerPolicy = link.referrerPolicy;
		if (link.crossOrigin === "use-credentials") fetchOpts.credentials = "include";
		else if (link.crossOrigin === "anonymous") fetchOpts.credentials = "omit";
		else fetchOpts.credentials = "same-origin";
		return fetchOpts;
	}
	function processPreload(link) {
		if (link.ep) return;
		link.ep = true;
		const fetchOpts = getFetchOpts(link);
		fetch(link.href, fetchOpts);
	}
})();
//#endregion
//#region src/translations.js
var translations = {
	sl: {
		navHome: "Domov",
		navStory: "Zgodba",
		navGallery: "Galerija",
		navMenu: "Meni",
		navReservation: "Kontakt",
		btnBookTable: "Kontakt",
		heroSubtitle: "Balkanska Kulinarična Umetnost",
		heroTitle1: "Dobrodošli",
		heroTitle2: "pri Ćevabdžinici Erniša",
		heroDesc: "Pristen okus žara, povzdignjen na nivo vrhunske kulinarike. Skrbno izbrane sestavine, tradicija in strast v vsakem grižljaju.",
		heroBtn: "Naš Meni",
		aboutTitle1: "Tradicija,",
		aboutTitle2: "na novo definirana.",
		aboutP1: "Družina Erniša vas vabi v sodobno zasnovan ambient v srcu Prekmurja, kjer tradicionalne balkanske specialitete zaživijo v novi, prefinjeni luči.",
		aboutP2: "Od naših korenin v vinogradništvu do premium čevabdžinice – naša predanost kvaliteti in gostoljubju ostaja naša glavna vodila. Ogenj, meso in skrbno izbrane začimbe ustvarjajo simfonijo okusov.",
		aboutBtn: "Doživite Ernišo",
		galSubtitle: "Vizualno Doživetje",
		galTitle1: "Naša ",
		galTitle2: "galerija",
		menuSubtitle: "Kulinarično popotovanje",
		menuTitle1: "Naš ",
		menuTitle2: "meni",
		catAll: "Vse",
		catStarters: "Tradicionalne predjedi",
		catGrill: "Glavne jedi z žara",
		catMain: "Glavne jedi",
		catSides: "Priloge",
		catSalad: "Solata kot priloga",
		catExtras: "Dodatki",
		catDesserts: "Sladice",
		mPaprika: "Marinirane pečene paprike",
		mPaprikaDesc: "Vložene paprike, pečene nad odprtim ognjem, marinirane s česnom, z rahlo sladkobo in nežno dimljeno aromo.",
		mCheese: "Pečen ovčji sir",
		mCheeseDesc: "Zlatorumeno pečen ovčji sir, postrežen s paradižnikom in česnom. Kremast in polnega okusa – pravi balkanski užitek za srce in čute.",
		mCuts: "Domači narezek",
		mCutsDesc: "Gorička šunka kot izbrana mesna specialiteta, postrežena s sirom, paradižnikom, vloženimi kumaricami, hrenom in domačo zaseko. Postrežena s kruhom ali toplo pečeno lepinjo.",
		mCevapi6: "Ćevapčići z žara – 6 kosov",
		mCevapi6Desc: "Šest sočno pečenih čevapčičev z izrazito začimbo in nežno dimljeno noto – popolni za manjši balkanski užitek.",
		mCevapi9: "Ćevapčići z žara – 9 kosov",
		mCevapi9Desc: "Devet pristnih klasik z žara, aromatičnih in polnega okusa – idealna porcija za prave gurmane.",
		mPleskavica: "Pleskavica iz žara",
		mPleskavicaDesc: "Popolno zapečena, aromatična in polnega okusa – pravi užitek na enem kosu.",
		mSausage: "Domača klobasa",
		mSausageDesc: "Postrežena z zlato ocvrtimi krompirjevimi rezinami, gorčico in svežim hrenom. Po želji tudi s kruhom in vloženim zeljem.",
		mWings: "Ocvrta piščančja krilca",
		mWingsDesc: "Hrskavo ocvrte, znotraj sočne in aromatične, postrežene s hrustljavim pomfrijem.",
		mCheeseSalad: "Pečen ovčji sir s solato",
		mCheeseSaladDesc: "Kremasta aroma in prijetna toplina s svežo, pisano solato.",
		mBeans: "Zapečeni prebranec",
		mBeansDesc: "Fižol tetovec z rdečo čebulo in balkanskimi začimbami, zapečen v pečici.",
		mBread: "Topla pečena lepinja",
		mBreadDesc: "Dve topli balkanski lepinji.",
		mBigSalad: "Velika solata",
		mBigSaladDesc: "Zeleni listi, paradižnik, paprika, kumarice, fižol, koruza, zelje.",
		mCabbage: "Sveže zelje",
		mCabbageDesc: "Hrustljavo, sveže narezano zelje, blago začinjeno.",
		mMixedSalad: "Mešana solata",
		mMixedSaladDesc: "Sveža sezonska zelenjava za popolno osvežitev.",
		mKajmak: "Kajmak",
		mKajmakDesc: "Kremasta balkanska mlečna specialiteta, blagega okusa in mazave teksture.",
		mAjvar: "Makedonski ajvar",
		mAjvarDesc: "Avtentičen domač ajvar (nepekoč ali pekoč).",
		mPindjur: "Pinđur",
		mPindjurDesc: "Balkanska specialiteta iz počasi kuhanih paprik in paradižnika, aromatična in polnega okusa.",
		mMustard: "Gorčica in čebula",
		mMustardDesc: "Gorčica iz Srbije ali porcija čebule s papriko.",
		mIcecream: "Mešano sladoledno razvajanje",
		mIcecreamDesc: "Tri kepice sladoleda po izbiri. Postreženo z ali brez stepene smetane.",
		mIcecreamBerries: "Sladoled z vročimi gozdnimi sadeži",
		mIcecreamBerriesDesc: "Tri kepice bourbon vanilijevega sladoleda z vročimi gozdnimi sadeži in stepeno smetano.",
		mCup: "Danska kupa / Švedska kupa",
		mCupDesc: "Tri kepice bourbon vanilijevega sladoleda s stepeno smetano in čokoladnim prelivom. / smetano in jajčnim likerjem.",
		mChoco: "Čokoladne sanje",
		mChocoDesc: "Rahel čokoladni sufle, postrežen z bourbon vanilijevim sladoledom in stepeno smetano.",
		mPancakes: "Domače palačinke",
		mPancakesDesc: "Dve sveže pečeni palačinki z nadevom po izbiri: Nutella ali marmelada. Postreženo z dvema kepicama bourbon vanilijevega sladoleda in stepeno smetano.",
		mChocoCup: "Čokoladna kupa",
		mChocoCupDesc: "Sladoled od bourbon vanilije in čokolade, čokoladni preliv in smetana.",
		mCheesecake: "Cheesecaake",
		mCheesecakeDesc: "Svež cheesecake s kepico sladoleda iz gozdnih sadežev in stepeno smetano.",
		mAffogato: "Affogato",
		mAffogatoDesc: "Kepica bourbon vanilijevega sladoleda prelita z vročim espressom.",
		mIcedCoffee: "Ledena kava",
		mIcedCoffeeDesc: "Bourbon vanilijev sladoled, dvojni espresso,mleko, smetana.",
		mVanillaScoop: "Kepica bourbon vanilije",
		mVanillaScoopDesc: "Prelita s baileys ali z jajčnim likerjem in stepeno smetano.",
		mCrocantCup: "Krokantna kupa",
		mCrocantCupDesc: "Sladoled od bourbon vanilije in čokolade, prelit s kavnim likerjem, posut s krokantom in obložen s stepeno smetano.",
		contactTitle1: "Stopite v ",
		contactTitle2: "stik",
		btnFullMenu: "Celoten Meni & Pijače",
		catSoftDrinks: "Brezalkoholne pijače",
		catHotDrinks: "Topli napitki",
		catBeer: "Pivo",
		catHouseWine: "Odprta vina",
		catWhiteWine: "Bela vina",
		catRedWine: "Rdeča vina / Rosé",
		catSparkling: "Penine",
		catCocktails: "Koktajli",
		catSpirits: "Žgane pijače",
		catSpecialWine: "Izbrana vina",
		dCola: "Coca Cola / Zero",
		dFanta: "Fanta",
		dSprite: "Sprite",
		dCockta: "Cockta",
		dIcedTea: "Ledeni čaj",
		dSchweppes: "Schweppes",
		dSchweppesDesc: "Tonic/ Bitter Lemon (0,25l)",
		dCedevita: "Cedevita",
		dCedevitaDesc: "limona / pomaranča",
		dRadenska: "Radenska",
		dRadenskaDesc: "Classic / Naturell",
		dFlavoredWater: "Voda z okusom",
		dJuice: "Sok",
		dJuiceDesc: "jabolčni / pomarančni",
		dLemonade: "Sveža limonada",
		dWater: "Postrežba vode",
		dEspresso: "Espresso",
		dEspressoDouble: "Espresso dvojni",
		dCoffeeLong: "Podaljšana kava",
		dCoffeeMilk: "Podaljšana kava z mlekom ali smetano",
		dCappuccino: "Cappuccino",
		dLatte: "Latte Macchiato",
		dIrish: "Irish Coffee",
		dIrishDesc: "Kava z 4 cl viskija in stepeno smetano.",
		dTea: "Čaj z limono",
		dTeaDesc: "različni okusi",
		dHotChoco: "Vroča čokolada",
		dMulledWine: "Kuhano vino",
		dMulledWineDesc: "belo ali rdeče",
		bLaskoDraft: "Laško točeno",
		bLaskoDark: "Laško temno",
		bLaskoZero: "Laško 0,0",
		bUnionZero: "Union - brezalkoholno",
		bUnionRadler: "Union Radler",
		bNiksicko: "Nikšićko",
		bNiksickoDesc: "Črna Gora (0,33l)",
		bJelen: "Jelen",
		bJelenDesc: "Srbija (0,33l / 0,50l)",
		bOzujsko: "Ožujsko",
		bOzujskoDesc: "Hrvaška (0,33l)",
		bHeinekenZero: "Heineken 0,0",
		bRadlerMix: "Radler",
		bRadlerMixDesc: "0,25 l Laško točenega piva in 0,25 l Sprite.",
		hwWhite: "Belo vino - Cuvée",
		hwWhiteDesc: "Slovenija – sveže, harmonično in sadno.",
		hwSpritzer: "Špricer",
		hwRed: "Rdeče vino - Vranec",
		hwRedDesc: "Severna Makedonija – suho, elegantno.",
		wwTraminec: "Traminec",
		wwTraminecDesc: "polsuho",
		wwMuskat: "Rumeni muškat",
		wwMuskatDesc: "polsuho",
		wwRizling: "Renski rizling",
		wwRizlingDesc: "suho",
		wwPinot: "Sivi pino",
		wwPinotDesc: "suho",
		wwChard: "Chardonnay",
		wwChardDesc: "suho",
		rwCuvee: "Afrodiziak - Cuvée",
		rwCuveeDesc: "suho, elegantno. Vranec, Merlot, Cabernet Sauvignon",
		rwRefosk: "Sladki refošk",
		rwRefoskDesc: "sladko, mehko in sadno",
		rwRose: "Rosé",
		rwRoseDesc: "suho, sveže",
		spSilver: "Srebrna",
		spSilverDesc: "suha, fino perlasta in elegantna",
		spRose: "Rosé",
		spRoseDesc: "sadna, harmonična in osvežujoča",
		spMuskat: "Muškatna",
		spMuskatDesc: "aromatična in sladkasta, dišeča ter rahlo igriva",
		cSpritz: "Aperol Spritz",
		cSpritzDesc: "Aperol, prosecco in pridih pomaranče – svež, rahlo grenak in poletno lahkoten.",
		cFizz: "Gin Fizz",
		cFizzDesc: "Gin, limona in soda – živahen, čist in osvežujoč.",
		cTonic: "Gin Tonic",
		cTonicDesc: "Gin s tonikom in svežo noto citrusov – klasičen in uravnotežen.",
		cVodka: "Vodka Bitter Lemon",
		cVodkaDesc: "Vodka z Bitter Lemon – prijetno grenak in osvežujoč.",
		sMaraska: "Šljivovica Maraska",
		sMaraskaDesc: "Slivovo žganje iz Zadra.",
		sBadel: "Šljivovica Badel",
		sBadelDesc: "Slivovo žganje iz Zagreba.",
		sSamar: "Rakija Šamar",
		sSamarDesc: "Tradicionalno žganje iz slive in kutine – mehko in značilnega okusa.",
		sPear: "Hruškovec",
		sPola: "Pola-Pola",
		sPolaDesc: "Pol šljivovice / pol hruškovca",
		sPelinkovac: "Pelinkovec",
		sTito: "TITO – zeliščni liker",
		sTravarica: "Travarica",
		sBlueberry: "Borovničevec",
		sViljamovka: "Viljamovka",
		sWalnut: "Orehovec - čokoladni",
		sMint: "Mentolov liker",
		sWhisky: "Ballantine’s - Whisky",
		sJager: "Jägermeister",
		sVodka: "Vodka",
		sGin: "Gin",
		sCynar: "Cynar",
		swPinotBlanc: "Pinot Blanc - Zvonko Bogdan (Srbija)",
		swPinotBlancDesc: "Sočno, sadno in bogato s kompleksno aromo. (suho)",
		swSauvBlanc: "Sauvignon Blanc - Zvonko Bogdan (Srbija)",
		swSauvBlancDesc: "Sveže, igrivo s citrusno sadnostjo, zelišči in mineralnim pridihom. (suho)",
		swTemnjanika: "Temnjanika - Chateau Kamnik (S. Makedonija)",
		swTemnjanikaDesc: "Aromatično z vonjem breskve in cvetja ter svežim, sadnim zaključkom. (polsuho)",
		swChardBarrel: "Chardonnay Barrel Fermented - Chateau Kamnik (S. Makedonija)",
		swChardBarrelDesc: "Korpulentno z izrazitimi barrique notami, zorjeno v francoskem hrastu, polnega telesa in bogatega značaja. (suho)",
		swAlexWhite: "Alexandria Premium White Cuvée - Tikveš (S. Makedonija)",
		swAlexWhiteDesc: "Elegantna zvrst iz izbranih belih sort iz sončne doline Tikveš. (suho)",
		swRoseSec: "Rosé Sec - Zvonko Bogdan (Srbija)",
		swRoseSecDesc: "Sočno, sadno in bogato s kompleksno aromo. (suho)",
		swAlexRose: "Alexandria Premium Cuvée Rosé - Tikveš (S. Makedonija)",
		swAlexRoseDesc: "Elegantna zvrst iz izbranih belih sort iz sončne doline Tikveš. (suho)",
		swCuvee1: "Cuvee No.1 - Zvonko Bogdan (Srbija)",
		swCuvee1Desc: "Trikrat zapored z zlatom na Decanter WWA, najprestižnejšem mednarodnem vinskem priznanju, nagrajena kompleksna zvrst z aromami robid, črnega ribeza in češenj ter dolgim, elegantnim zaključkom. (suho)",
		swSyrah: "Ten Barrels Syrah - Chateau Kamnik (S. Makedonija)",
		swSyrahDesc: "Kompleksen in uravnotežen syrah z aromami robidnic, začimb in čokolade, dolgim pookusom ter večkrat nagrajen na mednarodnih tekmovanjih. (suho)",
		swBabuna: "Babuna - Tikveš (S. Makedonija)",
		swBabunaDesc: "Drzno, sadno rdeče iz sort Plavec, Vranec in Shiraz z aromami robide, češnje in slive ter polnim, harmoničnim okusom z dolgim sočnim zaključkom. (suho)",
		swAlexRed: "Alexandria Premium Red Cuvée - Tikveš (S. Makedonija)",
		swAlexRedDesc: "Prefinjen rdeči cuvée razkriva bogate note robidnic, višenj in sliv, prepletene z začimbami in rahlo vaniljo, ter očara z mehko, žametno strukturo in dolgim, toplim zaključkom. (suho)",
		swPrestige: "Cuvée de Prestige MAGNUM - Chateau Kamnik (S. Makedonija)",
		swPrestigeDesc: "Izrazit rdeči cuvée v magnum steklenici, zorjen v hrastu, razkriva koncentrirane note temnega jagodičevja in začimb ter poln, žameten okus z dolgim, plemenitim zaključkom – popoln za 3–4 osebe in posebne priložnosti. (suho)",
		cat_predjedi: "ZA ZAČETEK",
		cat_glavne_zar: "Z ŽARA",
		cat_glavne: "JEDI IZ KUHINJE",
		cat_priloge: "PRILOGE",
		cat_solata: "SOLATE",
		cat_dodatki: "DODATKI",
		cat_sladice: "SLADICE",
		cat_pijace: "BREZALKOHOLNE PIJAČE",
		cat_topli: "TOPLI NAPITKI",
		cat_pivo: "PIVO",
		cat_odprta_vina: "ODPRTA VINA / HIŠNA IZBIRA",
		cat_bela_vina: "BELA VINA",
		cat_rdeca_vina: "RDEČA VINA / ROSÉ",
		cat_penine: "PENINE",
		cat_koktajli: "KOKTAJLI",
		cat_zgane: "ŽGANE PIJAČE",
		cat_izbrana_vina: "IZBRANA VINA",
		contactDesc: "Rezervacije sprejemamo izključno preko telefona. Za vsa ostala vprašanja, mnenja ali pripombe pa lahko uporabite spodnji obrazec.",
		locLabel: "Lokacija",
		telLabel: "Telefonska rezervacija",
		timeLabel: "Odpiralni čas",
		timeClosed: "Ponedeljek & Torek: ZAPRTO",
		timeWedFri: "Sreda – Petek: 16:30 – 21:00",
		timeSat: "Sobota: 12:00 – 23:00",
		timeSun: "Nedelja: 12:00 – 21:00",
		formName: "Ime in priimek",
		formNamePl: "Vaše ime in priimek",
		formEmail: "E-poštni naslov",
		formEmailPl: "Vaš e-poštni naslov",
		formMsg: "Sporočilo",
		formMsgPl: "Vaše vprašanje ali mnenje...",
		formSendBtn: "Pošlji sporočilo",
		cookieTitle: "Uporabljamo piškotke",
		cookieDesc: "Za najboljšo uporabniško izkušnjo na naši strani uporabljamo piškotke.",
		cookieBtn: "Sprejmem",
		footerTagline: "Tradicija, na novo definirana.",
		footerRes: "Kontakt",
		footerCopy: "© 2026 Ćevabdžinica Erniša. Spletno stran ustvaril: ",
		mMushSoup: "Gobova juha",
		mMushSoupDesc: "Kremna juha izključno iz svežih gob – brez moke ali krompirja.",
		mGoulashSoup: "Golaževa juha",
		mGoulashSoupDesc: "Krepka juha z mehko govedino in papriko.",
		mFriedChicken: "Panirani piščančji file",
		mFriedChickenDesc: "Zlatorumeno ocvrt, postrežen s pomfrijem.",
		mFries: "Pomfri",
		mFriesDesc: "Postrežen s kečapom ali majonezo.",
		mTomatoSalad: "Paradižnikova solata s čebulo",
		mTomatoSaladDesc: "",
		mMixedSaladSmall: "Mešana solata – mala",
		mMixedSaladSmallDesc: "",
		mMixedSaladBig: "Mešana solata – velika",
		mMixedSaladBigDesc: "",
		mOnion: "Porcija čebule začinjena s papriko",
		mOnionDesc: "",
		cat_premium_rakije: "PREMIUM RAKIJE",
		prZelja5: "Šljivovica Želja 5",
		prZelja5Desc: "Slivovo žganje, pridobljeno z dvojno destilacijo in mešanjem lokalnih sort sliv Čačanska rodna in Čačanska lepotica. Starano pet let v hrastovem sodu.",
		prZelja7: "Šljivovica Premium Želja 7",
		prZelja7Desc: "Slivovo žganje, pridobljeno z dvojno destilacijo in mešanjem lokalnih sort sliv Čačanska rodna in Čačanska lepotica. Starano sedem let v hrastovem sodu.",
		prZelja12: "Šljivovica Premium Želja 12",
		prZelja12Desc: "Slivovka, pridobljena z dvojno destilacijo in mešanjem sort sliv Čačanska rodna, Požegača in Crvena ranka. Starano 12 let v hrastovem sodu.",
		prPotpis: "Potpis Šljivovica 05",
		prPotpisDesc: "Slivovka, pridobljena z dvojno destilacijo v klasičnih 500l bakrenih kotlih. Sortiment - Crvena ranka, Čačanska lepotica in Čačanska rodna. 5 let zorjeno v srbskem hrastu.",
		prKrneta: "Krneta Šljiva",
		prKrnetaDesc: "Modra, močna in privlačna. Poln okus zrelih sliv in najlepših aromatičnih not. S skrbno obdelavo sadja je ohranjena najboljša kakovost in esenca popolnega sadnega okusa.",
		prAlchymia: "Rakija od šljive Alchymia",
		prAlchymiaDesc: "“Prepečnica šljivovica”, zorjena v hrastovem sodu iz domačega hrasta. Narejeno iz lokalnih sort sliv Čačanske rodne, Čačanske lepotice in Crvene ranke. Brez dodatkov, 100% naravna slivovka.",
		prOrnament: "Ornament rakija od šljive",
		prOrnamentDesc: "Ornament slivovka je jantarne barve, ki je značilna za izkušene destilate, zorene v hrastovih sodih. Ta proces zorenja destilatov obogati prevladujoč vonj in okus sliv s celo paleto pikantnih in rustikalnih not, ki jih pridobijo z mešanjem destilatov, starih od 4 do 18 let.",
		prPremiumRakija: "Šljiva Premium Rakija",
		prPremiumRakijaDesc: "Žganje, pridelano na tradicionalen način, z dvojno destilacijo zrelih plodov sliv iz lastnih sadovnjakov. Starano 5 let v sodih iz srbskega hrasta. Izrazita aroma kokosa, vanilije, dima, karamele. Po okusu spominja na sledove temne čokolade.",
		prZdanje: "Zdanje Šljiva",
		prZdanjeDesc: "Slivovka Zdanje, stara 20 let, je izjemno specifična in bogata pijača, ki nosi v sebi globoko tradicijo in značilen pečat časa. Izžareva globok in bogat okus z notami zrelih sliv, vanilije, hrasta in blagimi pikantnimi toni.",
		prGorda: "Gorda šljiva",
		prGordaDesc: "Vrhunsko slivovo žganje narejeno iz ročno obranih sliv iz lastnih nasadov in 7 let starano v hrastovih sodih. Izrazito jantarne barve, ki ga pridobi v toku zorenja v hrastovih sodih. Aroma suhe slive, blago pražene kave, vanilije in marcipana. Polnega okusa, ki spominja na rahlo praženo kavo, kakav in citruse.",
		prZavet: "Zavet 5",
		prZavetDesc: "Pridobljena z destilacijo tradicionalnih sort sliv. Znan okus in aroma dodatno oplemenjena s petletnim staranjem v hrastovem sodu. Svetlo olivno zelene barve. Polnega harmoničnega okusa, zmerne arome, pitna in blaga.",
		prHubert: "Hubert Šljiva barrique",
		prHubertDesc: "Slivovo žganje jantarne barve s prefinjeno cvetlično in vanilijevo aromo. Pridelano iz najboljših sort sliv na tradicionalen način, v bakrenih kotlih z dvojno destilacijo, po starem, preverjenem družinskem receptu. Poln sadni okus z izrazitimi tanini iz hrastovega soda, v katerem je starano najmanj 3 leta.",
		prGZ: "Gružanska Nit",
		prGZDesc: "Žganje je narejeno iz izbranih sort sliv iz lastnih nasadov. Narejeno po tradicionalnem postopku destilacije. Starano v hrastovih sodih 3 leta, kar da izjemno aromo in okus."
	},
	de: {
		navHome: "Startseite",
		navStory: "Geschichte",
		navGallery: "Galerie",
		navMenu: "Menü",
		navReservation: "Kontakt",
		btnBookTable: "Kontakt",
		heroSubtitle: "Balkanische Kochkunst",
		heroTitle1: "Willkommen",
		heroTitle2: "bei Ćevabdžinica Erniša",
		heroDesc: "Authentische Grillaromen, auf ein Fine-Dining-Erlebnis gehoben. Sorgfältig ausgewählte Zutaten, Tradition und Leidenschaft in jedem Bissen.",
		heroBtn: "Unser Menü",
		aboutTitle1: "Tradition,",
		aboutTitle2: "neu definiert.",
		aboutP1: "Die Familie Erniša lädt Sie in ein modern gestaltetes Ambiente im Herzen von Prekmurje ein, wo traditionelle Balkangepäck-Spezialitäten in neuem, raffiniertem Licht erstrahlen.",
		aboutP2: "Von unseren Wurzeln im Weinbau bis zur Premium-Ćevabdžinica – unser Engagement für Qualität und Gastfreundschaft bleibt unser Leitprinzip. Feuer, Fleisch und sorgfältig ausgewählte Gewürze schaffen eine Symphonie der Aromen.",
		aboutBtn: "Erniša Erleben",
		galSubtitle: "Visuelles Erlebnis",
		galTitle1: "Unsere ",
		galTitle2: "Galerie",
		menuSubtitle: "Eine Kulinarische Reise",
		menuTitle1: "Unser ",
		menuTitle2: "Menü",
		catAll: "Alle",
		catStarters: "Traditionelle Vorspeisen",
		catGrill: "Grill Hauptgerichte",
		catMain: "Hauptgerichte",
		catSides: "Beilagen",
		catSalad: "Beilagensalate",
		catExtras: "Extras",
		catDesserts: "Desserts",
		mPaprika: "Marinierte geröstete Paprika",
		mPaprikaDesc: "Eingelegte Paprika, über offenem Feuer geröstet, mit Knoblauch mariniert, mit leichter Süße und sanftem Raucharoma.",
		mCheese: "Gebackener Schafskäse",
		mCheeseDesc: "Goldbraun gebackener Schafskäse, serviert mit Tomaten und Knoblauch. Cremig und geschmacksintensiv – ein echter Balkan-Genuss.",
		mCuts: "Hausgemachter Aufschnitt",
		mCutsDesc: "Gorička-Schinken als ausgewählte Fleischspezialität, serviert mit Käse, Tomaten, Gewürzgurken, Meerrettich und hausgemachtem Schmalz. Serviert mit Brot oder warmem Fladenbrot.",
		mCevapi6: "Gegrillte Ćevapčići – 6 Stück",
		mCevapi6Desc: "Sechs saftig gegrillte Ćevapčići mit markanter Würze und zarter Rauchnote – perfekt für den kleinen Balkan-Genuss.",
		mCevapi9: "Gegrillte Ćevapčići – 9 Stück",
		mCevapi9Desc: "Neun authentische Grillklassiker, aromatisch und geschmacksintensiv – die ideale Portion für echte Feinschmecker.",
		mPleskavica: "Gegrillte Pleskavica",
		mPleskavicaDesc: "Popolno zapečena, aromatična in polnega okusa – pravi užitek na enem kosu.",
		mSausage: "Hausgemachte Wurst",
		mSausageDesc: "Serviert mit goldbraun gebratenen Kartoffelscheiben, Senf und frischem Meerrettich. Auf Wunsch auch mit Brot und eingelegtem Kohl.",
		mWings: "Gebratene Hähnchenflügel",
		mWingsDesc: "Knusprig frittiert, innen saftig und aromatisch, serviert mit knusprigen Pommes frites.",
		mCheeseSalad: "Gebackener Schafskäse mit Salat",
		mCheeseSaladDesc: "Cremiges Aroma und angenehme Wärme mit einem frischen, bunten Salat.",
		mBeans: "Gebackener Prebranac",
		mBeansDesc: "Tetovec-Bohnen mit roten Zwiebeln und Balkan-Gewürzen, im Ofen gebacken.",
		mBread: "Warmes Fladenbrot",
		mBreadDesc: "Zwei warme Balkan-Fladenbrote.",
		mBigSalad: "Großer Salat",
		mBigSaladDesc: "Grüne Blätter, Tomaten, Paprika, Gurken, Bohnen, Mais, Kohl.",
		mCabbage: "Frischer Kohl",
		mCabbageDesc: "Knuspriger, frisch geschnittener Kohl, mild gewürzt.",
		mMixedSalad: "Gemischter Salat",
		mMixedSaladDesc: "Frisches saisonales Gemüse für die perfekte Erfrischung.",
		mKajmak: "Kajmak",
		mKajmakDesc: "Cremige Balkan-Milchspezialität, mild im Geschmack und streichfähig.",
		mAjvar: "Mazedonischer Ajvar",
		mAjvarDesc: "Authentischer hausgemachter Ajvar (mild oder scharf).",
		mPindjur: "Pindjur",
		mPindjurDesc: "Balkan-Spezialität aus langsam gekochten Paprika und Tomaten, aromatisch und geschmacksintensiv.",
		mMustard: "Senf und Zwiebeln",
		mMustardDesc: "Serbischer Senf oder eine Portion Zwiebeln mit Paprika.",
		mIcecream: "Gemischter Eisgenuss",
		mIcecreamDesc: "Drei Kugeln Eis nach Wahl. Serviert mit oder ohne Sahnehaube.",
		mIcecreamBerries: "Eiscreme mit warmen Waldfrüchten",
		mIcecreamBerriesDesc: "Drei Kugeln Bourbon-Vanilleeis, verfeinert mit warmen Beeren und einem Hauch von Schlagsahne.",
		mCup: "Dänischer Pokal / Schwedischer Pokal",
		mCupDesc: "Drei Kugeln Bourbon-Vanilleeis, gekrönt mit Schlagsahne und verfeinert durch köstliche Schokoladensoße / Sahne und Eierlikör.",
		mChoco: "Schokoladenträume",
		mChocoDesc: "Ein zartes Schokoladensoufflé, begleitet von cremigem Bourbon-Vanilleeis und luftigem Schlagsahne.",
		mPancakes: "Selbstgemachte Pfannkuchen",
		mPancakesDesc: "Zwei frisch zubereitete Pfannkuchen, gefüllt nach Ihrem Wunsch: Nutella oder Marmelade. Begleitet von zwei Kugeln Bourbon-Vanilleeis und einem Hauch von Schlagsahne.",
		mChocoCup: "Schokoladenbecher",
		mChocoCupDesc: "Eiscreme aus Bourbon-Vanille und Schokoladen Eis, verfeinert mit köstlicher Schokoladensoße und einem Hauch von Schlagsahne.",
		mCheesecake: "Käsekuchen",
		mCheesecakeDesc: "Frischer Käsekuchen, begleitet von einer Kugel Waldbeereneis und einem Hauch von Schlagsahne.",
		mAffogato: "Affogato",
		mAffogatoDesc: "Eine Kugel Bourbon-Vanilleeis, gekrönt mit dampfendem Espresso.",
		mIcedCoffee: "Eiskaffee",
		mIcedCoffeeDesc: "Bourbon-Vanilleeis, doppelter Espresso, Milch, Schlagsahne.",
		mVanillaScoop: "Eine Prise Bourbon-Vanille",
		mVanillaScoopDesc: "Mit Baileys oder Eierlikör mit Schlagsahne verziert.",
		mCrocantCup: "Krokant Becher",
		mCrocantCupDesc: "Bourbon-Vanille- und Schokoladeneis, verfeinert mit Kaffeelikör, bestreut mit Haselnusskrokant und garniert mit Schlagsahne.",
		contactTitle1: "Kontakt ",
		contactTitle2: "aufnehmen",
		btnFullMenu: "Gesamtes Menü & Getränke",
		catSoftDrinks: "Alkoholfrei Getränke",
		catHotDrinks: "Warme Getränke",
		catBeer: "Biere",
		catHouseWine: "Offene Weine",
		catWhiteWine: "Weißweine",
		catRedWine: "Rotwein / Rosé",
		catSparkling: "Sekt",
		catCocktails: "Cocktails",
		catSpirits: "Spirituosen",
		catSpecialWine: "Erlesene Weine",
		dCola: "Coca Cola / Zero",
		dFanta: "Fanta",
		dSprite: "Sprite",
		dCockta: "Cockta",
		dIcedTea: "Eistee",
		dSchweppes: "Schweppes",
		dSchweppesDesc: "Tonic/ Bitter Lemon (0,25l)",
		dCedevita: "Cedevita",
		dCedevitaDesc: "Zitrone / Orange",
		dRadenska: "Wasser Radenska",
		dRadenskaDesc: "Classic / Naturell",
		dFlavoredWater: "Aromatisiertes Wasser",
		dJuice: "Saft",
		dJuiceDesc: "Apfel/ Orange",
		dLemonade: "Frische Limonade",
		dWater: "Tafelwasser",
		dEspresso: "Espresso",
		dEspressoDouble: "Espresso Doppio",
		dCoffeeLong: "Kaffee Creme",
		dCoffeeMilk: "Kaffee Creme mit Milch oder Sahne",
		dCappuccino: "Cappuccino",
		dLatte: "Latte Macchiato",
		dIrish: "Irisch Coffee",
		dIrishDesc: "mit 4cl Whiskey und Sahne",
		dTea: "Tee mit Zitrone",
		dTeaDesc: "verschiedene sorten",
		dHotChoco: "Heiße Schokolade",
		dMulledWine: "Glühwein",
		dMulledWineDesc: "weiß oder rot",
		bLaskoDraft: "Laško vom Fass",
		bLaskoDark: "Laško dunkel",
		bLaskoZero: "Laško 0,0",
		bUnionZero: "Union - alkoholfrei",
		bUnionRadler: "Union Radler",
		bNiksicko: "Nikšićko",
		bNiksickoDesc: "Montenegro (0,33l)",
		bJelen: "Jelen",
		bJelenDesc: "Serbien (0,33l / 0,50l)",
		bOzujsko: "Ožujsko",
		bOzujskoDesc: "Kroatien (0,33l)",
		bHeinekenZero: "Heineken 0,0",
		bRadlerMix: "Radler",
		bRadlerMixDesc: "Laško vom Fass 0,25l und Sprite 0,25l.",
		hwWhite: "weiß - Cuvée",
		hwWhiteDesc: "Slowenien - frisch, harmonisch, fruchtig.",
		hwSpritzer: "Weißweinschorle",
		hwRed: "rot - Vranec",
		hwRedDesc: "Nordmazedonien - trocken, elegant.",
		wwTraminec: "Gewürztraminer",
		wwTraminecDesc: "halbtrocken",
		wwMuskat: "Gelber Muskateller",
		wwMuskatDesc: "halbtrocken",
		wwRizling: "Rheinriesling",
		wwRizlingDesc: "trocken",
		wwPinot: "Grauburgunder",
		wwPinotDesc: "trocken",
		wwChard: "Chardonnay",
		wwChardDesc: "trocken",
		rwCuvee: "Afrodiziak - Cuvée",
		rwCuveeDesc: "trocken, elegant. Vranec, Merlot, Cabernet Sauvignon.",
		rwRefosk: "Süßer Refošk (Refosco)",
		rwRefoskDesc: "lieblich, weich und fruchtbetont.",
		rwRose: "Rosé",
		rwRoseDesc: "trocken, frisch.",
		spSilver: "Silber Sekt",
		spSilverDesc: "trocken, feinperlig und elegant.",
		spRose: "Rosé Sekt",
		spRoseDesc: "fruchtig, harmonisch und erfrischend.",
		spMuskat: "Muskateller Sekt",
		spMuskatDesc: "aromatisch-süß, duftig und leicht verspiel.",
		cSpritz: "Aperol Spritz",
		cSpritzDesc: "Aperol, Prosecco und ein Hauch Orange – frisch, leicht bitter und sommerlich.",
		cFizz: "Gin Fizz",
		cFizzDesc: "Gin, Zitrone und Soda – spritzig, klar und belebend.",
		cTonic: "Gin Tonic",
		cTonicDesc: "Gin mit Tonic Water und frischer Zitrusnote – klassisch und ausgewogen.",
		cVodka: "Wodka Bitter Lemon",
		cVodkaDesc: "Wodka mit Bitter Lemon – angenehm herb und erfrischend.",
		sMaraska: "Šljivovica Maraska",
		sMaraskaDesc: "Pflaumenschnaps aus Zadar.",
		sBadel: "Šljivovica Badel",
		sBadelDesc: "Pflaumenschnaps aus Zagreb.",
		sSamar: "Rakija Šamar",
		sSamarDesc: "Traditioneller Brand aus Pflaume und Quitte – weich und charaktervoll.",
		sPear: "Hruškovec",
		sPola: "Pola-Pola",
		sPolaDesc: "halb Šljivovica / halb Hruškovec.",
		sPelinkovac: "Pelinkovac",
		sTito: "TITO – Kräuterlikör",
		sTravarica: "Travarica",
		sBlueberry: "Borovničevec",
		sViljamovka: "Viljamovka",
		sWalnut: "Orehovec Chocolate",
		sMint: "Pfefferminzlikör",
		sWhisky: "Ballantine’s - Whisky",
		sJager: "Jägermeister",
		sVodka: "Wodka",
		sGin: "Gin",
		sCynar: "Cynar",
		swPinotBlanc: "Pinot Blanc - Zvonko Bogdan (Serbien)",
		swPinotBlancDesc: "Saftig, fruchtbetont und reichhaltig mit komplexer Aromatik und eleganter Struktur. (trocken)",
		swSauvBlanc: "Sauvignon Blanc - Zvonko Bogdan (Serbien)",
		swSauvBlancDesc: "Frisch und lebendig mit Zitrusfrucht und feinen Kräuternoten. (trocken)",
		swTemnjanika: "Temnjanika - Chateau Kamnik (Nordmazedonien)",
		swTemnjanikaDesc: "Aromatisch mit Duft von Pfirsich und Blüten, begleitet von einem frischen, fruchtigen Abgang. (halbtrocken)",
		swChardBarrel: "Chardonnay Barrique - Chateau Kamnik (Nordmazedonien)",
		swChardBarrelDesc: "Kräftig und vollmundig mit ausgeprägten Barrique-Noten, im französischen Eichenfass gereift – viel Tiefe und Charakter. (trocken)",
		swAlexWhite: "Alexandria Premium White Cuvée - Tikveš (Nordmazedonien)",
		swAlexWhiteDesc: "Eleganter Cuvée aus ausgewählten weißen Rebsorten aus dem sonnigen Tikveš-Tal. (trocken)",
		swRoseSec: "Rosé Sec - Zvonko Bogdan (Serbien)",
		swRoseSecDesc: "Saftig, fruchtbetont und harmonisch mit feiner, komplexer Aromatik und lebendiger Frische. (trocken)",
		swAlexRose: "Alexandria Premium Cuvée Rosé - Tikveš (Nordmazedonien)",
		swAlexRoseDesc: "Cuvée aus ausgewählten Rebsorten aus dem sonnigen Tikveš-Tal – frisch, ausgewogen und stilvoll im Charakter. (trocken)",
		swCuvee1: "Cuvee No.1 - Zvonko Bogdan (Serbien)",
		swCuvee1Desc: "Dreifach mit Gold bei den Decanter World Wine Awards ausgezeichnet. Komplexe Cuvée mit Aromen von Brombeeren, schwarzer Johannisbeere und Kirsche sowie langem, eleganten Abgang. (trocken)",
		swSyrah: "Ten Barrels Syrah - Chateau Kamnik (Nordmazedonien)",
		swSyrahDesc: "Komplexer und ausgewogener Syrah mit Noten von Brombeeren, Gewürzen und dunkler Schokolade, langem Nachhall und mehrfach international prämiert. (trocken)",
		swBabuna: "Babuna - Tikveš (Nordmazedonien)",
		swBabunaDesc: "Ausdrucksstarker Rotwein aus Plavec, Vranec und Shiraz mit Aromen von Brombeeren, Kirschen und Pflaumen, vollmundig und harmonisch mit saftigem, langem Finale. (trocken)",
		swAlexRed: "Alexandria Premium Cuvée - Tikveš (Nordmazedonien)",
		swAlexRedDesc: "Eleganter roter Cuvée mit reichen Noten von Brombeeren, Sauerkirschen und Pflaumen, fein verwoben mit Gewürzen und einem Hauch Vanille. Weiche, samtige Struktur und warmer, anhaltender Abgang. (trocken)",
		swPrestige: "Cuvée de Prestige MAGNUM - Chateau Kamnik (Nordmazedonien)",
		swPrestigeDesc: "Charaktervolle, im Eichenfass gereifter Cuvée in der Magnumflasche mit konzentrierten Aromen dunkler Beeren und Gewürze. Vollmundig, samtig und lang im Abgang – ideal für 3–4 Personen und besondere Anlässe. (trocken)",
		cat_predjedi: "VORSPEISEN",
		cat_glavne_zar: "HAUPTSPEISEN VOM GRILL",
		cat_glavne: "HAUPTSPEISEN",
		cat_priloge: "BEILAGEN",
		cat_solata: "SALATE",
		cat_dodatki: "EXTRAS",
		cat_sladice: "NACHSPEISEN",
		cat_pijace: "ALKOHOLFREI GETRÄNKE",
		cat_topli: "WARME GETRÄNKE",
		cat_pivo: "BIERE",
		cat_odprta_vina: "OFFENE WEINE HAUSWEINE",
		cat_bela_vina: "WEIßWEINE",
		cat_rdeca_vina: "ROTWEIN / ROSÉ",
		cat_penine: "SEKT",
		cat_koktajli: "COCKTAILS / LONGDRINKS",
		cat_zgane: "SPIRITUOSEN AUS DEM BALKAN",
		cat_izbrana_vina: "ERLESENE WEINE",
		contactDesc: "Wir nehmen Reservierungen ausschließlich telefonisch entgegen. Für alle weiteren Fragen, Feedback oder Meinungen nutzen Sie bitte das untenstehende Formular.",
		locLabel: "Standort",
		telLabel: "Telefonische Reservierung",
		timeLabel: "Öffnungszeiten",
		timeClosed: "Montag & Dienstag: GESCHLOSSEN",
		timeWedFri: "Mittwoch – Freitag: 16:30 – 21:00",
		timeSat: "Samstag: 12:00 – 23:00",
		timeSun: "Sonntag: 12:00 – 21:00",
		formName: "Vollständiger Name",
		formNamePl: "Ihr vollständiger Name",
		formEmail: "E-Mail-Adresse",
		formEmailPl: "Ihre E-Mail-Adresse",
		formMsg: "Nachricht",
		formMsgPl: "Ihre Frage oder Feedback...",
		formSendBtn: "Nachricht Senden",
		cookieTitle: "Wir verwenden Cookies",
		cookieDesc: "Wir verwenden Cookies, um Ihnen das beste Erlebnis auf unserer Website zu bieten.",
		cookieBtn: "Akzeptieren",
		footerTagline: "Tradition, neu definiert.",
		footerRes: "Kontakt",
		footerCopy: "© 2026 Ćevabdžinica Erniša. Website erstellt von: ",
		cat_premium_rakije: "PREMIUM RAKIJA",
		mMushSoup: "Pilzsuppe",
		mMushSoupDesc: "Cremige Suppe ausschließlich aus frischen Pilzen – ohne Mehl oder Kartoffeln.",
		mGoulashSoup: "Gulaschsuppe",
		mGoulashSoupDesc: "Deftige Suppe mit zartem Rindfleisch und Paprika.",
		mFriedChicken: "Paniertes Hähnchenfilet",
		mFriedChickenDesc: "Goldbraun frittiert, serviert mit Pommes frites.",
		mFries: "Pommes frites",
		mFriesDesc: "Serviert mit Ketchup oder Mayonnaise.",
		mTomatoSalad: "Tomatensalat mit Zwiebeln",
		mTomatoSaladDesc: "",
		mMixedSaladSmall: "Gemischter Salat - Klein",
		mMixedSaladSmallDesc: "",
		mMixedSaladBig: "Gemischter Salat - Groß",
		mMixedSaladBigDesc: "",
		mOnion: "Portion Zwiebeln mit Paprika gewürzt",
		mOnionDesc: "",
		prZelja5: "Šljivovica Želja 5",
		prZelja5Desc: "Pflaumenbrand, gewonnen durch doppelte Destillation und Mischung lokaler Pflaumensorten Čačanska rodna und Čačanska lepotica. Fünf Jahre im Eichenfass gereift.",
		prZelja7: "Šljivovica Premium Želja 7",
		prZelja7Desc: "Pflaumenbrand, gewonnen durch doppelte Destillation und Mischung lokaler Pflaumensorten Čačanska rodna und Čačanska lepotica. Sieben Jahre im Eichenfass gereift.",
		prZelja12: "Šljivovica Premium Želja 12",
		prZelja12Desc: "Pflaumenbrand, gewonnen durch doppelte Destillation und Mischung der Pflaumensorten Čačanska rodna, Požegača und Crvena ranka. 12 Jahre im Eichenfass gereift.",
		prPotpis: "Potpis Šljivovica 05",
		prPotpisDesc: "Pflaumenbrand, gewonnen durch doppelte Destillation in klassischen 500l-Kupferkesseln. Sortiment - Crvena ranka, Čačanska lepotica und Čačanska rodna. 5 Jahre in serbischer Eiche gereift.",
		prKrneta: "Krneta Šljiva",
		prKrnetaDesc: "Blau, stark und attraktiv. Voller Geschmack reifer Pflaumen und der schönsten aromatischen Noten. Durch sorgfältige Verarbeitung der Früchte bleibt die höchste Qualität und Essenz des perfekten Fruchtgeschmacks erhalten.",
		prAlchymia: "Alchymia Pflaumenbrand",
		prAlchymiaDesc: "“Prepečnica” Pflaumenbrand, gereift im Eichenfass aus heimischer Eiche. Hergestellt aus den lokalen Pflaumensorten Čačanska rodna, Čačanska lepotica und Crvena ranka. Ohne Zusätze, 100% natürlicher Pflaumenbrand.",
		prOrnament: "Ornament Pflaumenbrand",
		prOrnamentDesc: "Ornament Pflaumenbrand hat eine bernsteinfarbene Tönung, die typisch für erfahrene, in Eichenfässern gereifte Destillate ist. Dieser Reifeprozess bereichert den vorherrschenden Duft und Geschmack der Pflaume um eine ganze Palette von würzigen und rustikalen Noten, die durch die Mischung von 4 bis 18 Jahre alten Destillaten entstehen.",
		prPremiumRakija: "Šljiva Premium Rakija",
		prPremiumRakijaDesc: "Nach traditioneller Art hergestellter Brand durch doppelte Destillation reifer Pflaumen aus eigenen Obstgärten. 5 Jahre in serbischen Eichenfässern gereift. Deutliches Aroma von Kokosnuss, Vanille, Rauch, Karamell. Der Geschmack erinnert an Spuren von dunkler Schokolade.",
		prZdanje: "Zdanje Šljiva",
		prZdanjeDesc: "Zdanje Pflaumenbrand, 20 Jahre alt, ist ein außergewöhnlich spezifisches und reiches Getränk, das eine tiefe Tradition und ein deutliches Zeichen der Zeit in sich trägt. Es strahlt einen tiefen und reichen Geschmack mit Noten von reifen Pflaumen, Vanille, Eiche und milden würzigen Tönen aus.",
		prGorda: "Gorda Šljiva",
		prGordaDesc: "Premium-Pflaumenbrand aus handgepflückten Pflaumen aus eigenen Obstgärten, 7 Jahre in Eichenfässern gereift. Deutlich bernsteinfarben, die er während der Reifung in Eichenfässern erhält. Aroma von getrockneten Pflaumen, leicht geröstetem Kaffee, Vanille und Marzipan. Voller Geschmack, der an leicht gerösteten Kaffee, Kakao und Zitrusfrüchte erinnert.",
		prZavet: "Zavet 5",
		prZavetDesc: "Gewonnen durch die Destillation traditioneller Pflaumensorten. Ein bekannter Geschmack und ein Aroma, das durch die fünfjährige Reifung im Eichenfass weiter angereichert wird. Hellolivgrüne Farbe. Voller harmonischer Geschmack, moderates Aroma, sehr trinkbar und mild.",
		prHubert: "Hubert Šljiva barrique",
		prHubertDesc: "Bernsteinfarbener Pflaumenbrand mit subtilem blumigem und Vanillearoma. Hergestellt aus den besten Pflaumensorten nach traditioneller Art in Kupferkesseln durch doppelte Destillation, nach einem alten, bewährten Familienrezept. Voller fruchtiger Geschmack mit ausgeprägten Tanninen aus dem Eichenfass, in dem er mindestens 3 Jahre gereift ist.",
		prGZ: "Gružanska Nit",
		prGZDesc: "Brand hergestellt aus ausgewählten Pflaumensorten aus eigenen Obstgärten. Hergestellt nach traditionellem Destillationsverfahren. 3 Jahre in Eichenfässern gereift, was ein außergewöhnliches Aroma und Geschmack verleiht."
	},
	hu: {
		navHome: "Főoldal",
		navStory: "Történetünk",
		navGallery: "Galéria",
		navMenu: "Étlap",
		navReservation: "Kapcsolat",
		btnBookTable: "Kapcsolat",
		heroSubtitle: "Balkáni Kulináris Művészet",
		heroTitle1: "Üdvözöljük a",
		heroTitle2: "Ćevabdžinica Erniša-ban",
		heroDesc: "Az igazi balkáni grill íze prémium szinten. Gondosan válogatott alapanyagok, hagyomány és szenvedély minden falatban.",
		heroBtn: "Étlapunk",
		aboutTitle1: "Hagyomány,",
		aboutTitle2: "újraértelmezve.",
		aboutP1: "Az Erniša család meghívja Önt egy modern környezetbe a Muravidék szívében, ahol a hagyományos balkáni specialitások új, kifinomult fényben tündökölnek.",
		aboutP2: "Borászati gyökereinktől a prémium ćevabdžinica-ig – a minőség és a vendégszeretet iránti elkötelezettségünk marad a fő vezérelvünk. A tűz, a hús és a gondosan válogatott fűszerek az ízek szimfóniáját alkotják.",
		aboutBtn: "Élje át az Ernišát",
		galSubtitle: "Vizuális Élmény",
		galTitle1: "A mi ",
		galTitle2: "galériánk",
		menuSubtitle: "Kulináris utazás",
		menuTitle1: "A mi ",
		menuTitle2: "étlapunk",
		catAll: "Összes",
		catStarters: "Hagyományos előételek",
		catGrill: "Főételek grillről",
		catMain: "Főételek",
		catSides: "Köretek",
		catSalad: "Saláta köretek",
		catExtras: "Extrák",
		catDesserts: "Desszertek",
		mPaprika: "Marinált sült paprika",
		mPaprikaDesc: "Nyílt lángon sült, fokhagymával marinált paprika, enyhén édeskés, lágy füstös aromával.",
		mCheese: "Sült juhsajt",
		mCheeseDesc: "Aranybarnára sült juhsajt, paradicsommal és fokhagymával tálalva. Krémes és gazdag ízvilág – igazi balkáni élvezet.",
		mCuts: "Házi felvágott tál",
		mCutsDesc: "Goričko sonka, mint válogatott hússpecialitás, sajttal, paradicsommal, csemegeuborkával, tormával és házi zsírral. Kenyérrel vagy meleg sült lepénnyel tálalva.",
		mCevapi6: "Grillezett Ćevapčići – 6 db",
		mCevapi6Desc: "Hat szaftosra sütött ćevapčići, jellegzetes fűszerezéssel és finom füstös jegyekkel – tökéletes egy kisebb balkáni élvezethez.",
		mCevapi9: "Grillezett Ćevapčići – 9 db",
		mCevapi9Desc: "Kilenc igazi grillezett klasszikus, aromás és gazdag ízvilág – ideális adag az igazi ínyenceknek.",
		mPleskavica: "Grillezett Pleskavica",
		mPleskavicaDesc: "Tökéletesen átsült, aromás és telt ízű – igazi élvezet egy darabban.",
		mSausage: "Házi kolbász",
		mSausageDesc: "Aranybarnára sült burgonyaszeletekkel, mustárral és friss tormával tálalva. Kérésre kenyérrel és savanyú káposztával is.",
		mWings: "Sült csirkeszárnyak",
		mWingsDesc: "Kívül ropogós, belül szaftos és aromás, ropogós hasábburgonyával tálalva.",
		mCheeseSalad: "Sült juhsajt salátával",
		mCheeseSaladDesc: "Krémes aroma és kellemes melegség friss, színes salátával párosítva.",
		mBeans: "Sült Prebranac (bab)",
		mBeansDesc: "Sütőben sült Tetovac bab lila hagymával és balkáni fűszerekkel.",
		mBread: "Meleg sült lepény (Lepinja)",
		mBreadDesc: "Két meleg balkáni lepény.",
		mBigSalad: "Nagy saláta",
		mBigSaladDesc: "Zöld levelek, paradicsom, paprika, uborka, bab, kukorica, káposzta.",
		mCabbage: "Friss káposzta",
		mCabbageDesc: "Ropogós, friss vágott káposzta, enyhén fűszerezve.",
		mMixedSalad: "Vegyes saláta",
		mMixedSaladDesc: "Friss szezonális zöldségek a tökéletes felfrissüléshez.",
		mKajmak: "Kajmak",
		mKajmakDesc: "Krémes balkáni tejkülönlegesség, enyhe ízű és kenhető textúrájú.",
		mAjvar: "Macedón Ajvár",
		mAjvarDesc: "Autentikus házi ajvár (csemege vagy csípős).",
		mPindjur: "Pinđur",
		mPindjurDesc: "Balkáni specialitás lassan főtt paprikából és paradicsomból, aromás és gazdag ízű.",
		mMustard: "Mustár és hagyma",
		mMustardDesc: "Szerb mustár vagy egy adag hagyma paprikával.",
		mIcecream: "Fagylalt klasszikus",
		mIcecreamDesc: "Három gombóc fagylalt tetszés szerint. Tejszínhabbal vagy anélkül tálalva.",
		mIcecreamBerries: "Fagylalt meleg erdei gyümölcsökkel",
		mIcecreamBerriesDesc: "Három gombóc bourbon vanília fagylalt meleg erdei gyümölcsökkel és tejszínhabbal.",
		mCup: "Dán kehely / Svéd kehely",
		mCupDesc: "Három gombóc bourbon vanília fagylalt tejszínhabbal és csokoládéöntettel / tejszínnel és tojáslikőrrel.",
		mChoco: "Csokoládé álmok",
		mChocoDesc: "Könnyű csokoládé szuflé, bourbon vanília fagylalttal és tejszínhabbal tálalva.",
		mPancakes: "Házi palacsinta",
		mPancakesDesc: "Két frissen sült palacsinta választott töltelékkel: Nutella vagy lekvár. Két gombóc bourbon vanília fagylalttal és tejszínhabbal tálalva.",
		mChocoCup: "Csokoládékehely",
		mChocoCupDesc: "Bourbon vanília és csokoládé fagylalt, ízletes csokoládéöntettel és tejszínhabbal.",
		mCheesecake: "Sajttorta",
		mCheesecakeDesc: "Friss sajttorta, egy gombóc erdei gyümölcsös fagylalttal és tejszínhabbal.",
		mAffogato: "Affogato",
		mAffogatoDesc: "Egy gombóc Bourbon vanília fagylalt gőzölgő eszpresszóval nyakon öntve.",
		mIcedCoffee: "Jegeskávé",
		mIcedCoffeeDesc: "Bourbon vanília fagylalt, dupla eszpresszó, tej, tejszínhab.",
		mVanillaScoop: "Egy gombóc Bourbon vanília",
		mVanillaScoopDesc: "Baileys-szel vagy tojáslikőrrel és tejszínhabbal díszítve.",
		mCrocantCup: "Krokant kehely",
		mCrocantCupDesc: "Bourbon vanília és csokoládé fagylalt kávélikőrrel finomítva, mogyorókrokanttal megszórva és tejszínhabbal díszítve.",
		contactTitle1: "Lépjen ",
		contactTitle2: "kapcsolatba velünk",
		btnFullMenu: "Teljes Étlap és Itallap",
		catSoftDrinks: "Üdítőitalok",
		catHotDrinks: "Forró italok",
		catBeer: "Sörök",
		catHouseWine: "Folyó borok",
		catWhiteWine: "Fehérborok",
		catRedWine: "Vörösborok / Rosé",
		catSparkling: "Pezsgők",
		catCocktails: "Koktélok",
		catSpirits: "Röviditalok",
		catSpecialWine: "Különleges borok",
		dCola: "Coca Cola / Zero",
		dFanta: "Fanta",
		dSprite: "Sprite",
		dCockta: "Cockta",
		dIcedTea: "Jegestea",
		dSchweppes: "Schweppes",
		dSchweppesDesc: "Tonic/ Bitter Lemon (0,25l)",
		dCedevita: "Cedevita",
		dCedevitaDesc: "citrom / narancs",
		dRadenska: "Radenska ásványvíz",
		dRadenskaDesc: "Klasszikus / Mentes",
		dFlavoredWater: "Ízesített víz",
		dJuice: "Gyümölcslé",
		dJuiceDesc: "alma / narancs",
		dLemonade: "Friss limonádé",
		dWater: "Vízszolgáltatás",
		dEspresso: "Eszpresszó",
		dEspressoDouble: "Dupla eszpresszó",
		dCoffeeLong: "Hosszú kávé",
		dCoffeeMilk: "Hosszú kávé tejjel vagy tejszínnel",
		dCappuccino: "Cappuccino",
		dLatte: "Latte Macchiato",
		dIrish: "Ír kávé",
		dIrishDesc: "Kávé 4 cl whiskyvel és tejszínhabbal.",
		dTea: "Tea citrommal",
		dTeaDesc: "különböző ízek",
		dHotChoco: "Forró csokoládé",
		dMulledWine: "Forralt bor",
		dMulledWineDesc: "fehér vagy vörös",
		bLaskoDraft: "Laško csapolt",
		bLaskoDark: "Laško barna",
		bLaskoZero: "Laško 0,0",
		bUnionZero: "Union - alkoholmentes",
		bUnionRadler: "Union Radler",
		bNiksicko: "Nikšićko",
		bNiksickoDesc: "Montenegró (0,33l)",
		bJelen: "Jelen",
		bJelenDesc: "Szerbia (0,33l / 0,50l)",
		bOzujsko: "Ožujsko",
		bOzujskoDesc: "Horvátország (0,33l)",
		bHeinekenZero: "Heineken 0,0",
		bRadlerMix: "Radler Mix",
		bRadlerMixDesc: "0,25 l csapolt Laško sör és 0,25 l Sprite.",
		hwWhite: "Fehérbor - Cuvée",
		hwWhiteDesc: "Szlovénia – friss, harmonikus és gyümölcsös.",
		hwSpritzer: "Fröccs",
		hwRed: "Vörösbor - Vranec",
		hwRedDesc: "Észak-Macedónia – száraz, elegáns.",
		wwTraminec: "Tramini",
		wwTraminecDesc: "félszáraz",
		wwMuskat: "Sárgamuskotály",
		wwMuskatDesc: "félszáraz",
		wwRizling: "Rajnai Rizling",
		wwRizlingDesc: "száraz",
		wwPinot: "Szürkebarát (Pinot Gris)",
		wwPinotDesc: "száraz",
		wwChard: "Chardonnay",
		wwChardDesc: "száraz",
		rwCuvee: "Afrodiziak - Cuvée",
		rwCuveeDesc: "száraz, elegáns. Vranec, Merlot, Cabernet Sauvignon",
		rwRefosk: "Édes Refošk",
		rwRefoskDesc: "édes, lágy és gyümölcsös",
		rwRose: "Rosé",
		rwRoseDesc: "száraz, friss",
		spSilver: "Ezüst pezsgő",
		spSilverDesc: "száraz, finom buborékos és elegáns",
		spRose: "Rosé pezsgő",
		spRoseDesc: "gyümölcsös, harmonikus és frissítő",
		spMuskat: "Muskotály pezsgő",
		spMuskatDesc: "aromás és édeskés, illatos és enyhén játékos",
		cSpritz: "Aperol Spritz",
		cSpritzDesc: "Aperol, prosecco és egy leheletnyi narancs – friss, enyhén kesernyés és nyárias.",
		cFizz: "Gin Fizz",
		cFizzDesc: "Gin, citrom és szóda – élénk, tiszta és frissítő.",
		cTonic: "Gin Tonic",
		cTonicDesc: "Gin tonikkal és friss citrusos jegyekkel – klasszikus és kiegyensúlyozott.",
		cVodka: "Vodka Bitter Lemon",
		cVodkaDesc: "Vodka Bitter Lemonnel – kellemesen fanyar és frissítő.",
		sMaraska: "Šljivovica Maraska",
		sMaraskaDesc: "Szilvapálinka Zadar-ból.",
		sBadel: "Šljivovica Badel",
		sBadelDesc: "Szilvapálinka Zágráb-ból.",
		sSamar: "Rakija Šamar",
		sSamarDesc: "Hagyományos párlat szilvából és birsalmából – lágy és karakteres.",
		sPear: "Körtepálinka (Hruškovec)",
		sPola: "Pola-Pola",
		sPolaDesc: "Fele szilvapálinka / fele körtepálinka",
		sPelinkovac: "Pelinkovac",
		sTito: "TITO – gyógynövénylikőr",
		sTravarica: "Travarica (Gyógynövénypálinka)",
		sBlueberry: "Áfonyalikőr",
		sViljamovka: "Vilmoskörte pálinka",
		sWalnut: "Diólikőr - csokoládés",
		sMint: "Menta likőr",
		sWhisky: "Ballantine’s - Whisky",
		sJager: "Jägermeister",
		sVodka: "Vodka",
		sGin: "Gin",
		sCynar: "Cynar",
		swPinotBlanc: "Pinot Blanc - Zvonko Bogdan (Szerbia)",
		swPinotBlancDesc: "Szaftos, gyümölcsös és gazdag komplex aromával. (száraz)",
		swSauvBlanc: "Sauvignon Blanc - Zvonko Bogdan (Szerbia)",
		swSauvBlancDesc: "Friss, játékos citrusos gyümölcsösséggel, gyógynövényekkel és ásványos jegyekkel. (száraz)",
		swTemnjanika: "Temnjanika - Chateau Kamnik (É. Macedónia)",
		swTemnjanikaDesc: "Aromás, barack- és virágillattal, friss, gyümölcsös lecsengéssel. (félszáraz)",
		swChardBarrel: "Chardonnay Barrel Fermented - Chateau Kamnik (É. Macedónia)",
		swChardBarrelDesc: "Testes, kifejezett barrique jegyekkel, francia tölgyfahordóban érlelve, gazdag karakterrel. (száraz)",
		swAlexWhite: "Alexandria Premium White Cuvée - Tikveš (É. Macedónia)",
		swAlexWhiteDesc: "Elegáns házasítás válogatott fehér fajtákból a napsütötte Tikveš völgyből. (száraz)",
		swRoseSec: "Rosé Sec - Zvonko Bogdan (Szerbia)",
		swRoseSecDesc: "Szaftos, gyümölcsös és gazdag komplex aromával. (száraz)",
		swAlexRose: "Alexandria Premium Cuvée Rosé - Tikveš (É. Macedónia)",
		swAlexRoseDesc: "Elegáns házasítás válogatott fehér fajtákból a napsütötte Tikveš völgyből. (száraz)",
		swCuvee1: "Cuvee No.1 - Zvonko Bogdan (Szerbia)",
		swCuvee1Desc: "Háromszor egymás után aranyérmes a Decanter WWA-n. Komplex házasítás szeder, feketeribizli és cseresznye aromákkal, hosszú, elegáns lecsengéssel. (száraz)",
		swSyrah: "Ten Barrels Syrah - Chateau Kamnik (É. Macedónia)",
		swSyrahDesc: "Komplex és kiegyensúlyozott syrah szeder, fűszerek és csokoládé aromákkal, hosszú utóízzel, többszörösen díjazott. (száraz)",
		swBabuna: "Babuna - Tikveš (É. Macedónia)",
		swBabunaDesc: "Merész, gyümölcsös vörösbor Plavec, Vranec és Shiraz fajtákból szeder, cseresznye és szilva aromákkal, telt, harmonikus ízzel. (száraz)",
		swAlexRed: "Alexandria Premium Red Cuvée - Tikveš (É. Macedónia)",
		swAlexRedDesc: "Kifinomult vörös cuvée, mely szeder, meggy és szilva gazdag jegyeit tárja fel, fűszerekkel és egy csipetnyi vaníliával átszőve. Lágy, bársonyos textúra. (száraz)",
		swPrestige: "Cuvée de Prestige MAGNUM - Chateau Kamnik (É. Macedónia)",
		swPrestigeDesc: "Kifejező vörös cuvée magnum palackban, tölgyfahordóban érlelve, sötét bogyós gyümölcsök és fűszerek koncentrált jegyeivel. Testes, bársonyos íz – tökéletes 3–4 személyre. (száraz)",
		cat_predjedi: "ELŐÉTELEK",
		cat_glavne_zar: "GRILL",
		cat_glavne: "FŐÉTELEK",
		cat_priloge: "KÖRETEK",
		cat_solata: "SALÁTÁK",
		cat_dodatki: "EXTRÁK",
		cat_sladice: "DESSZERTEK",
		cat_pijace: "ÜDÍTŐITALOK",
		cat_topli: "FORRÓ ITALOK",
		cat_pivo: "SÖR",
		cat_odprta_vina: "FOLYÓ BOROK / HÁZ BORA",
		cat_bela_vina: "FEHÉRBOROK",
		cat_rdeca_vina: "VÖRÖSBOROK / ROSÉ",
		cat_penine: "PEZSGŐK",
		cat_koktajli: "KOKTÉLOK",
		cat_zgane: "RÖVIDITALOK",
		cat_izbrana_vina: "KÜLÖNLEGES BOROK",
		contactDesc: "Asztalfoglalást kizárólag telefonon fogadunk. Minden egyéb kérdés, vélemény vagy észrevétel esetén használja az alábbi űrlapot.",
		locLabel: "Helyszín",
		telLabel: "Telefonos asztalfoglalás",
		timeLabel: "Nyitvatartás",
		timeClosed: "Hétfő és Kedd: ZÁRVA",
		timeWedFri: "Szerda – Péntek: 16:30 – 21:00",
		timeSat: "Szombat: 12:00 – 23:00",
		timeSun: "Vasárnap: 12:00 – 21:00",
		formName: "Név és vezetéknév",
		formNamePl: "Az Ön neve",
		formEmail: "E-mail cím",
		formEmailPl: "Az Ön e-mail címe",
		formMsg: "Üzenet",
		formMsgPl: "Az Ön kérdése vagy véleménye...",
		formSendBtn: "Üzenet küldése",
		cookieTitle: "Sütiket használunk",
		cookieDesc: "A legjobb felhasználói élmény érdekében weboldalunkon sütiket használunk.",
		cookieBtn: "Elfogadom",
		footerTagline: "Hagyomány, újraértelmezve.",
		footerRes: "Kapcsolat",
		footerCopy: "© 2026 Ćevabdžinica Erniša. Weboldalt készítette: ",
		cat_premium_rakije: "PRÉMIUM RAKIJA",
		mMushSoup: "Gombaleves",
		mMushSoupDesc: "Krémes leves kizárólag friss gombából – liszt és burgonya nélkül.",
		mGoulashSoup: "Gulyásleves",
		mGoulashSoupDesc: "Kiadós leves omlós marhahússal és paprikával.",
		mFriedChicken: "Rántott csirkemell",
		mFriedChickenDesc: "Aranybarnára sütve, hasábburgonyával tálalva.",
		mFries: "Hasábburgonya",
		mFriesDesc: "Ketchuppal vagy majonézzel tálalva.",
		mTomatoSalad: "Paradicsomsaláta hagymával",
		mTomatoSaladDesc: "",
		mMixedSaladSmall: "Vegyes saláta - Kicsi",
		mMixedSaladSmallDesc: "",
		mMixedSaladBig: "Vegyes saláta - Nagy",
		mMixedSaladBigDesc: "",
		mOnion: "Adag hagyma paprikával fűszerezve",
		mOnionDesc: "",
		prZelja5: "Šljivovica Želja 5",
		prZelja5Desc: "Szilvapálinka, kétszeres lepárlással és a helyi Čačanska rodna valamint Čačanska lepotica szilvafajták keverésével. Öt évig tölgyfahordóban érlelve.",
		prZelja7: "Šljivovica Premium Želja 7",
		prZelja7Desc: "Szilvapálinka, kétszeres lepárlással és a helyi Čačanska rodna valamint Čačanska lepotica szilvafajták keverésével. Hét évig tölgyfahordóban érlelve.",
		prZelja12: "Šljivovica Premium Želja 12",
		prZelja12Desc: "Szilvapálinka, kétszeres lepárlással és a Čačanska rodna, Požegača, valamint Crvena ranka szilvafajták keverésével. 12 évig tölgyfahordóban érlelve.",
		prPotpis: "Potpis Šljivovica 05",
		prPotpisDesc: "Klasszikus 500 literes rézüstökben, kétszeres lepárlással készült szilvapálinka. Fajták: Crvena ranka, Čačanska lepotica és Čačanska rodna. 5 évig szerb tölgyfában érlelve.",
		prKrneta: "Krneta Šljiva",
		prKrnetaDesc: "Kék, erős és vonzó. Az érett szilva telt íze a legszebb aromás jegyekkel. A gondos gyümölcsfeldolgozás megőrzi a legkiválóbb minőséget és a tökéletes gyümölcsíz esszenciáját.",
		prAlchymia: "Alchymia Szilvapálinka",
		prAlchymiaDesc: "“Prepečnica” szilvapálinka, hazai tölgyfahordóban érlelve. Helyi Čačanska rodna, Čačanska lepotica és Crvena ranka szilvafajtákból. Adalékanyagok nélkül, 100%-ban természetes szilvapálinka.",
		prOrnament: "Ornament Szilvapálinka",
		prOrnamentDesc: "Az Ornament szilvapálinka borostyán színű, ami a tölgyfahordóban érlelt tapasztalt párlatokra jellemző. Ez az érlelési folyamat a szilva uralkodó illatát és ízét a 4-től 18 évig érlelt párlatok keverésével kapott fűszeres és rusztikus jegyek egész palettájával gazdagítja.",
		prPremiumRakija: "Šljiva Premium Rakija",
		prPremiumRakijaDesc: "Saját gyümölcsösből származó érett szilva kétszeres lepárlásával, hagyományos módon előállított pálinka. 5 évig szerb tölgyfahordóban érlelve. Határozott kókusz, vanília, füst és karamell aroma. Íze étcsokoládé nyomaira emlékeztet.",
		prZdanje: "Zdanje Šljiva",
		prZdanjeDesc: "A 20 éves Zdanje szilvapálinka egy kivételesen egyedi és gazdag ital, amely mély hagyományokat és az idő múlásának egyértelmű lenyomatát hordozza. Mély és gazdag ízvilágot sugároz, érett szilva, vanília, tölgyfa és enyhe fűszeres tónusok jegyeivel.",
		prGorda: "Gorda Šljiva",
		prGordaDesc: "Prémium szilvapálinka saját gyümölcsösből származó, kézzel szedett szilvából, 7 évig tölgyfahordóban érlelve. Kifejezett borostyán színe a tölgyfahordós érlelés során alakul ki. Aszalt szilva, enyhén pörkölt kávé, vanília és marcipán aromája. Telt íz, amely enyhén pörkölt kávéra, kakaóra és citrusfélékre emlékeztet.",
		prZavet: "Zavet 5",
		prZavetDesc: "Hagyományos szilvafajták lepárlásával nyert párlat. Az ismert ízt és aromát további öt éves tölgyfahordós érlelés gazdagítja. Világos olívazöld színű. Telt harmonikus íz, mérsékelt aroma, nagyon iható és lágy.",
		prHubert: "Hubert Šljiva barrique",
		prHubertDesc: "Borostyán színű szilvapálinka, finom virág- és vanília aromával. A legjobb szilvafajtákból hagyományos módon, rézüstben kétszeres lepárlással, régi, bevált családi recept alapján készül. Telt gyümölcsös íz kifejezett tanninokkal a tölgyfahordóból, amelyben legalább 3 évig érlelték.",
		prGZ: "Gružanska Nit",
		prGZDesc: "Saját gyümölcsösből származó válogatott szilvafajtákból készült pálinka. Hagyományos lepárlási eljárással. 3 évig tölgyfahordóban érlelve, ami kivételes aromát és ízt kölcsönöz neki."
	},
	en: {
		navHome: "Home",
		navStory: "Story",
		navGallery: "Gallery",
		navMenu: "Menu",
		navReservation: "Contact",
		btnBookTable: "Contact",
		heroSubtitle: "Balkan Culinary Art",
		heroTitle1: "Welcome",
		heroTitle2: "to Ćevabdžinica Erniša",
		heroDesc: "Authentic grill flavors elevated to a fine dining experience. Carefully selected ingredients, tradition, and passion in every bite.",
		heroBtn: "Our Menu",
		aboutTitle1: "Tradition,",
		aboutTitle2: "redefined.",
		aboutP1: "The Erniša family invites you to a modernly designed ambiance in the heart of Prekmurje, where traditional Balkan specialties come alive in a new, refined light.",
		aboutP2: "From our roots in winemaking to a premium ćevabdžinica – our dedication to quality and hospitality remains our guiding principle. Fire, meat, and carefully selected spices create a symphony of flavors.",
		aboutBtn: "Experience Erniša",
		galSubtitle: "Visual Experience",
		galTitle1: "Our ",
		galTitle2: "gallery",
		menuSubtitle: "A Culinary Journey",
		menuTitle1: "Our ",
		menuTitle2: "menu",
		catAll: "All",
		catStarters: "Traditional Starters",
		catGrill: "Grill Main Courses",
		catMain: "Main Courses",
		catSides: "Side Dishes",
		catSalad: "Side Salads",
		catExtras: "Extras",
		catDesserts: "Desserts",
		mPaprika: "Marinated Roasted Peppers",
		mPaprikaDesc: "Pickled peppers, roasted over an open fire, marinated with garlic, with a slight sweetness and gentle smoky aroma.",
		mCheese: "Baked Sheep Cheese",
		mCheeseDesc: "Golden-brown baked sheep cheese, served with tomatoes and garlic. Creamy and full of flavor – a true Balkan delight.",
		mCuts: "Homemade Cold Cuts",
		mCutsDesc: "Gorička ham as a selected meat specialty, served with cheese, tomatoes, pickled cucumbers, horseradish, and homemade lard. Served with bread or warm flatbread.",
		mCevapi6: "Grilled Ćevapčići – 6 pieces",
		mCevapi6Desc: "Six juicy grilled ćevapčići with distinct seasoning and a gentle smoky note – perfect for a smaller Balkan delight.",
		mCevapi9: "Grilled Ćevapčići – 9 pieces",
		mCevapi9Desc: "Nine authentic grill classics, aromatic and full of flavor – an ideal portion for true gourmets.",
		mPleskavica: "Grilled Pleskavica",
		mPleskavicaDesc: "Popolno zapečena, aromatična in polnega okusa – pravi užitek na enem kosu.",
		mSausage: "Homemade Sausage",
		mSausageDesc: "Served with golden-fried potato slices, mustard, and fresh horseradish. Also available with bread and pickled cabbage upon request.",
		mWings: "Fried Chicken Wings",
		mWingsDesc: "Crispy fried, juicy and aromatic inside, served with crispy french fries.",
		mCheeseSalad: "Baked Sheep Cheese with Salad",
		mCheeseSaladDesc: "Creamy aroma and pleasant warmth with a fresh, colorful salad.",
		mBeans: "Baked Prebranac",
		mBeansDesc: "Tetovec beans with red onion and Balkan spices, baked in the oven.",
		mBread: "Warm Baked Flatbread",
		mBreadDesc: "Two warm Balkan flatbreads.",
		mBigSalad: "Large Salad",
		mBigSaladDesc: "Green leaves, tomatoes, peppers, cucumbers, beans, corn, cabbage.",
		mCabbage: "Fresh Cabbage",
		mCabbageDesc: "Crispy, freshly sliced cabbage, mildly seasoned.",
		mMixedSalad: "Mixed Salad",
		mMixedSaladDesc: "Fresh seasonal vegetables for perfect refreshment.",
		mKajmak: "Kajmak",
		mKajmakDesc: "Creamy Balkan dairy specialty, mild in flavor with a spreadable texture.",
		mAjvar: "Macedonian Ajvar",
		mAjvarDesc: "Authentic homemade ajvar (mild or spicy).",
		mPindjur: "Pindjur",
		mPindjurDesc: "Balkan specialty made from slow-cooked peppers and tomatoes, aromatic and full of flavor.",
		mMustard: "Mustard and Onion",
		mMustardDesc: "Serbian mustard or a portion of onion with paprika.",
		mIcecream: "Ice Cream Classic",
		mIcecreamDesc: "Three scoops of ice cream of your choice. Served with or without whipped cream.",
		mIcecreamBerries: "Ice Cream with Warm Wild Berries",
		mIcecreamBerriesDesc: "Three scoops of bourbon vanilla ice cream with warm wild berries and whipped cream.",
		mCup: "Danish Cup / Swedish Cup",
		mCupDesc: "Three scoops of bourbon vanilla ice cream with whipped cream and chocolate sauce / cream and egg liqueur.",
		mChoco: "Chocolate Dreams",
		mChocoDesc: "Light chocolate soufflé, served with bourbon vanilla ice cream and whipped cream.",
		mPancakes: "Homemade Pancakes",
		mPancakesDesc: "Two freshly baked pancakes with your choice of filling: Nutella or marmalade. Served with two scoops of bourbon vanilla ice cream and whipped cream.",
		mChocoCup: "Chocolate Cup",
		mChocoCupDesc: "Bourbon vanilla and chocolate ice cream, chocolate sauce and whipped cream.",
		mCheesecake: "Cheesecake",
		mCheesecakeDesc: "Fresh cheesecake with a scoop of wild berry ice cream and whipped cream.",
		mAffogato: "Affogato",
		mAffogatoDesc: "A scoop of bourbon vanilla ice cream topped with steaming hot espresso.",
		mIcedCoffee: "Iced Coffee",
		mIcedCoffeeDesc: "Bourbon vanilla ice cream, double espresso, milk, whipped cream.",
		mVanillaScoop: "Scoop of Bourbon Vanilla",
		mVanillaScoopDesc: "Topped with Baileys or egg liqueur and whipped cream.",
		mCrocantCup: "Croquant Cup",
		mCrocantCupDesc: "Bourbon vanilla and chocolate ice cream, topped with coffee liqueur, sprinkled with croquant and garnished with whipped cream.",
		contactTitle1: "Get in ",
		contactTitle2: "touch",
		contactDesc: "We accept reservations exclusively by phone. For any other questions, feedback, or opinions, please use the form below.",
		locLabel: "Location",
		telLabel: "Phone Reservation",
		timeLabel: "Opening Hours",
		timeClosed: "Monday & Tuesday: CLOSED",
		timeWedFri: "Wednesday – Friday: 16:30 – 21:00",
		timeSat: "Saturday: 12:00 – 23:00",
		timeSun: "Sunday: 12:00 – 21:00",
		formName: "Full Name",
		formNamePl: "Your full name",
		formEmail: "Email Address",
		formEmailPl: "Your email address",
		formMsg: "Message",
		formMsgPl: "Your question or feedback...",
		formSendBtn: "Send Message",
		cookieTitle: "We use cookies",
		cookieDesc: "We use cookies to ensure you get the best experience on our website.",
		cookieBtn: "Accept",
		footerTagline: "Tradition, redefined.",
		footerRes: "Contact",
		footerCopy: "© 2026 Ćevabdžinica Erniša. Website created by: ",
		cat_predjedi: "STARTERS",
		cat_glavne_zar: "FROM THE GRILL",
		cat_glavne: "MAIN COURSES",
		cat_priloge: "SIDE DISHES",
		cat_solata: "SALADS",
		cat_dodatki: "EXTRAS",
		cat_sladice: "DESSERTS",
		cat_pijace: "NON-ALCOHOLIC DRINKS",
		cat_topli: "HOT BEVERAGES",
		cat_pivo: "BEER",
		cat_odprta_vina: "HOUSE WINES",
		cat_bela_vina: "WHITE WINES",
		cat_rdeca_vina: "RED WINE / ROSÉ",
		cat_penine: "SPARKLING WINE",
		cat_koktajli: "COCKTAILS",
		cat_zgane: "SPIRITS",
		cat_izbrana_vina: "SELECTED WINES",
		cat_premium_rakije: "PREMIUM RAKIJA",
		mMushSoup: "Mushroom Soup",
		mMushSoupDesc: "Creamy soup made exclusively from fresh mushrooms – no flour or potatoes.",
		mGoulashSoup: "Goulash Soup",
		mGoulashSoupDesc: "Hearty soup with tender beef and paprika.",
		mFriedChicken: "Breaded Chicken Fillet",
		mFriedChickenDesc: "Golden-brown fried, served with french fries.",
		mFries: "French Fries",
		mFriesDesc: "Served with ketchup or mayonnaise.",
		mTomatoSalad: "Tomato Salad with Onion",
		mTomatoSaladDesc: "",
		mMixedSaladSmall: "Mixed Salad - Small",
		mMixedSaladSmallDesc: "",
		mMixedSaladBig: "Mixed Salad - Large",
		mMixedSaladBigDesc: "",
		mOnion: "Portion of Onion seasoned with paprika",
		mOnionDesc: "",
		btnFullMenu: "Celoten Meni & Pijače",
		dCola: "Coca Cola / Zero",
		dFanta: "Fanta",
		dSprite: "Sprite",
		dCockta: "Cockta",
		dIcedTea: "Ledeni čaj",
		dSchweppes: "Schweppes",
		dSchweppesDesc: "Tonic/ Bitter Lemon (0.25l)",
		dCedevita: "Cedevita",
		dCedevitaDesc: "lemon / orange",
		dRadenska: "Radenska",
		dRadenskaDesc: "Classic / Naturell",
		dFlavoredWater: "Flavored water",
		dJuice: "Juice",
		dJuiceDesc: "apple / orange",
		dLemonade: "Fresh lemonade",
		dWater: "Table water",
		dEspresso: "Espresso",
		dEspressoDouble: "Double Espresso",
		dCoffeeLong: "Lungo",
		dCoffeeMilk: "Coffee with milk or cream",
		dCappuccino: "Cappuccino",
		dLatte: "Latte Macchiato",
		dIrish: "Irish Coffee",
		dIrishDesc: "Coffee with 4 cl of whiskey and whipped cream.",
		dTea: "Tea with lemon",
		dTeaDesc: "various flavors",
		dHotChoco: "Hot chocolate",
		dMulledWine: "Mulled wine",
		dMulledWineDesc: "white or red",
		bLaskoDraft: "Laško točeno",
		bLaskoDark: "Laško temno",
		bLaskoZero: "Laško 0,0",
		bUnionZero: "Union - non-alcoholic",
		bUnionRadler: "Union Radler",
		bNiksicko: "Nikšićko",
		bNiksickoDesc: "Montenegro (0.33l)",
		bJelen: "Jelen",
		bJelenDesc: "Serbia (0.33l / 0.50l)",
		bOzujsko: "Ožujsko",
		bOzujskoDesc: "Croatia (0.33l)",
		bHeinekenZero: "Heineken 0,0",
		bRadlerMix: "Radler",
		bRadlerMixDesc: "0.25 l Laško draft beer and 0.25 l Sprite.",
		hwWhite: "White wine - Cuvée",
		hwWhiteDesc: "Slovenia – fresh, harmonious, and fruity.",
		hwSpritzer: "White wine spritzer",
		hwRed: "Red wine - Vranec",
		hwRedDesc: "North Macedonia – dry, elegant.",
		wwTraminec: "Gewürztraminer",
		wwTraminecDesc: "semi-dry",
		wwMuskat: "Yellow Muscat",
		wwMuskatDesc: "semi-dry",
		wwRizling: "Rhein Riesling",
		wwRizlingDesc: "dry",
		wwPinot: "Pinot Gris",
		wwPinotDesc: "dry",
		wwChard: "Chardonnay",
		wwChardDesc: "dry",
		rwCuvee: "Afrodiziak - Cuvée",
		rwCuveeDesc: "dry, elegant. Vranec, Merlot, Cabernet Sauvignon",
		rwRefosk: "Sweet Refošk",
		rwRefoskDesc: "sweet, soft, and fruity",
		rwRose: "Rosé",
		rwRoseDesc: "dry, fresh",
		spSilver: "Silver",
		spSilverDesc: "dry, fine pearls, and elegant",
		spRose: "Rosé",
		spRoseDesc: "fruity, harmonious, and refreshing",
		spMuskat: "Muscat",
		spMuskatDesc: "aromatic and sweet, fragrant and slightly playful",
		cSpritz: "Aperol Spritz",
		cSpritzDesc: "Aperol, prosecco, and a touch of orange – fresh, slightly bitter, and summery.",
		cFizz: "Gin Fizz",
		cFizzDesc: "Gin, lemon, and soda – vibrant, clear, and refreshing.",
		cTonic: "Gin Tonic",
		cTonicDesc: "Gin with tonic and a fresh citrus note – classic and balanced.",
		cVodka: "Vodka Bitter Lemon",
		cVodkaDesc: "Vodka with Bitter Lemon – pleasantly bitter and refreshing.",
		sMaraska: "Šljivovica Maraska",
		sMaraskaDesc: "Plum brandy from Zadar.",
		sBadel: "Šljivovica Badel",
		sBadelDesc: "Plum brandy from Zagreb.",
		sSamar: "Rakija Šamar",
		sSamarDesc: "Traditional brandy from plum and quince – soft and distinct in flavor.",
		sPear: "Pear Brandy",
		sPola: "Half-Half",
		sPolaDesc: "Half plum brandy / half pear brandy",
		sPelinkovac: "Pelinkovac (Herbal Liqueur)",
		sTito: "TITO – herbal liqueur",
		sTravarica: "Travarica (Herbal Brandy)",
		sBlueberry: "Blueberry Liqueur",
		sViljamovka: "Williams Pear Brandy",
		sWalnut: "Walnut - chocolate",
		sMint: "Mint Liqueur",
		sWhisky: "Ballantine’s - Whisky",
		sJager: "Jägermeister",
		sVodka: "Vodka",
		sGin: "Gin",
		sCynar: "Cynar",
		swPinotBlanc: "Pinot Blanc - Zvonko Bogdan (Srbija)",
		swPinotBlancDesc: "Juicy, fruity, and rich with a complex aroma. (dry)",
		swSauvBlanc: "Sauvignon Blanc - Zvonko Bogdan (Srbija)",
		swSauvBlancDesc: "Fresh, playful with citrus fruitiness, herbs, and a mineral touch. (dry)",
		swTemnjanika: "Temnjanika - Chateau Kamnik (S. Makedonija)",
		swTemnjanikaDesc: "Aromatic with the scent of peach and flowers, and a fresh, fruity finish. (semi-dry)",
		swChardBarrel: "Chardonnay Barrel Fermented - Chateau Kamnik (S. Makedonija)",
		swChardBarrelDesc: "Full-bodied with distinct barrique notes, aged in French oak, rich in character. (dry)",
		swAlexWhite: "Alexandria Premium White Cuvée - Tikveš (S. Makedonija)",
		swAlexWhiteDesc: "An elegant blend of selected white varieties from the sunny Tikveš valley. (dry)",
		swRoseSec: "Rosé Sec - Zvonko Bogdan (Srbija)",
		swRoseSecDesc: "Juicy, fruity, and rich with a complex aroma. (dry)",
		swAlexRose: "Alexandria Premium Cuvée Rosé - Tikveš (S. Makedonija)",
		swAlexRoseDesc: "An elegant blend of selected white varieties from the sunny Tikveš valley. (dry)",
		swCuvee1: "Cuvee No.1 - Zvonko Bogdan (Srbija)",
		swCuvee1Desc: "Three times in a row awarded gold at the Decanter WWA. A complex blend with aromas of blackberries, blackcurrants, and cherries, and a long, elegant finish. (dry)",
		swSyrah: "Ten Barrels Syrah - Chateau Kamnik (S. Makedonija)",
		swSyrahDesc: "A complex and balanced Syrah with aromas of blackberries, spices, and chocolate, a long aftertaste, and repeatedly awarded in international competitions. (dry)",
		swBabuna: "Babuna - Tikveš (S. Makedonija)",
		swBabunaDesc: "A bold, fruity red from Plavec, Vranec, and Shiraz varieties with aromas of blackberry, cherry, and plum, and a full, harmonious taste with a long juicy finish. (dry)",
		swAlexRed: "Alexandria Premium Red Cuvée - Tikveš (S. Makedonija)",
		swAlexRedDesc: "A refined red cuvée revealing rich notes of blackberries, sour cherries, and plums, intertwined with spices and a hint of vanilla, captivating with a soft, velvety structure and a long, warm finish. (dry)",
		swPrestige: "Cuvée de Prestige MAGNUM - Chateau Kamnik (S. Makedonija)",
		swPrestigeDesc: "A distinct red cuvée in a magnum bottle, aged in oak, revealing concentrated notes of dark berries and spices, and a full, velvety taste with a long, noble finish – perfect for 3–4 people and special occasions. (dry)",
		catSoftDrinks: "Brezalkoholne pijače",
		catHotDrinks: "Topli napitki",
		catBeer: "Pivo",
		catHouseWine: "Odprta vina",
		catWhiteWine: "Bela vina",
		catRedWine: "Rdeča vina / Rosé",
		catSparkling: "Penine",
		catCocktails: "Koktajli",
		catSpirits: "Žgane pijače",
		catSpecialWine: "Izbrana vina",
		prZelja5: "Šljivovica Želja 5",
		prZelja5Desc: "Plum brandy obtained by double distillation and blending of local plum varieties Čačanska rodna and Čačanska lepotica. Aged for five years in an oak barrel.",
		prZelja7: "Šljivovica Premium Želja 7",
		prZelja7Desc: "Plum brandy obtained by double distillation and blending of local plum varieties Čačanska rodna and Čačanska lepotica. Aged for seven years in an oak barrel.",
		prZelja12: "Šljivovica Premium Želja 12",
		prZelja12Desc: "Plum brandy obtained by double distillation and blending of plum varieties Čačanska rodna, Požegača, and Crvena ranka. Aged for 12 years in an oak barrel.",
		prPotpis: "Potpis Šljivovica 05",
		prPotpisDesc: "Plum brandy obtained by double distillation in classic 500l copper stills. Assortment - Crvena ranka, Čačanska lepotica, and Čačanska rodna. Aged for 5 years in Serbian oak.",
		prKrneta: "Krneta Šljiva",
		prKrnetaDesc: "Blue, strong, and attractive. Full taste of ripe plums and the finest aromatic notes. With careful fruit processing, the highest quality and essence of perfect fruity flavor are preserved.",
		prAlchymia: "Alchymia Plum Brandy",
		prAlchymiaDesc: "“Prepečnica” plum brandy, aged in an oak barrel made from local oak. Made from local plum varieties Čačanska rodna, Čačanska lepotica, and Crvena ranka. No additives, 100% natural plum brandy.",
		prOrnament: "Ornament Plum Brandy",
		prOrnamentDesc: "Ornament plum brandy has an amber color, typical for experienced distillates aged in oak barrels. This aging process enriches the predominant aroma and taste of plums with a full palette of spicy and rustic notes, acquired by blending distillates aged from 4 to 18 years.",
		prPremiumRakija: "Šljiva Premium Rakija",
		prPremiumRakijaDesc: "Brandy produced in a traditional way, by double distillation of ripe plums from our own orchards. Aged for 5 years in Serbian oak barrels. Distinct aroma of coconut, vanilla, smoke, caramel. The taste is reminiscent of traces of dark chocolate.",
		prZdanje: "Zdanje Šljiva",
		prZdanjeDesc: "Zdanje plum brandy, aged for 20 years, is an exceptionally specific and rich drink that carries a deep tradition and a distinct mark of time. It radiates a deep and rich flavor with notes of ripe plums, vanilla, oak, and mild spicy tones.",
		prGorda: "Gorda Šljiva",
		prGordaDesc: "Premium plum brandy made from hand-picked plums from our own orchards and aged for 7 years in oak barrels. Distinctly amber color acquired during aging in oak barrels. Aroma of dried plum, mildly roasted coffee, vanilla, and marzipan. Full flavor reminiscent of mildly roasted coffee, cocoa, and citrus.",
		prZavet: "Zavet 5",
		prZavetDesc: "Obtained by distilling traditional plum varieties. A known flavor and aroma further enriched by five years of aging in an oak barrel. Light olive green color. Full harmonious flavor, moderate aroma, highly drinkable and mild.",
		prHubert: "Hubert Šljiva barrique",
		prHubertDesc: "Amber-colored plum brandy with a subtle floral and vanilla aroma. Produced from the best plum varieties in a traditional way, in copper stills by double distillation, according to an old, proven family recipe. Full fruity taste with pronounced tannins from the oak barrel, in which it has aged for at least 3 years.",
		prGZ: "Gružanska Nit",
		prGZDesc: "Brandy made from selected plum varieties from our own orchards. Produced using a traditional distillation process. Aged in oak barrels for 3 years, which gives an exceptional aroma and taste."
	}
};
//#endregion
//#region src/main.js
document.addEventListener("DOMContentLoaded", () => {
	const langBtns = document.querySelectorAll(".lang-btn");
	const elementsToTranslate = document.querySelectorAll("[data-i18n]");
	const placeholdersToTranslate = document.querySelectorAll("[data-i18n-pl]");
	if (window.location.hash === "#rezervacija" || window.location.pathname === "/rezervacija" || window.location.pathname === "/rezervacija/") window.location.replace("/#kontakt");
	function setLanguage(lang) {
		if (!translations[lang]) return;
		localStorage.setItem("selectedLang", lang);
		langBtns.forEach((btn) => {
			if (btn.dataset.lang === lang) btn.classList.add("active");
			else btn.classList.remove("active");
		});
		elementsToTranslate.forEach((el) => {
			const key = el.dataset.i18n;
			if (translations[lang][key]) el.innerText = translations[lang][key];
		});
		placeholdersToTranslate.forEach((el) => {
			const key = el.dataset.i18nPl;
			if (translations[lang][key]) el.placeholder = translations[lang][key];
		});
	}
	setLanguage(localStorage.getItem("selectedLang") || "sl");
	langBtns.forEach((btn) => {
		btn.addEventListener("click", (e) => {
			setLanguage(e.target.dataset.lang);
		});
	});
	const header = document.getElementById("header");
	window.addEventListener("scroll", () => {
		if (!header) return;
		if (window.scrollY > 50) header.classList.add("scrolled");
		else header.classList.remove("scrolled");
	});
	const hamburger = document.querySelector(".hamburger");
	const navLinks = document.querySelector(".nav-links");
	const links = document.querySelectorAll(".nav-links li a");
	if (hamburger) hamburger.addEventListener("click", () => {
		hamburger.classList.toggle("active");
		navLinks.classList.toggle("active");
	});
	if (links) links.forEach((link) => {
		link.addEventListener("click", () => {
			hamburger.classList.remove("active");
			navLinks.classList.remove("active");
		});
	});
	const filterBtns = document.querySelectorAll(".category-btn");
	const menuItems = document.querySelectorAll(".menu-item");
	filterBtns.forEach((btn) => {
		btn.addEventListener("click", () => {
			filterBtns.forEach((b) => b.classList.remove("active"));
			btn.classList.add("active");
			const filter = btn.dataset.category;
			menuItems.forEach((item) => {
				if (filter === "vse" || item.dataset.category === filter) {
					item.style.display = "flex";
					setTimeout(() => {
						item.style.opacity = "1";
						item.style.transform = "translateY(0)";
					}, 50);
				} else {
					item.style.opacity = "0";
					item.style.transform = "translateY(20px)";
					setTimeout(() => {
						item.style.display = "none";
					}, 300);
				}
			});
		});
	});
	const slides = document.querySelectorAll(".gallery-slide");
	if (slides.length > 0) {
		let currentSlide = 0;
		setInterval(() => {
			slides[currentSlide].classList.remove("active");
			currentSlide = (currentSlide + 1) % slides.length;
			slides[currentSlide].classList.add("active");
		}, 4e3);
	}
	const observer = new IntersectionObserver((entries) => {
		entries.forEach((entry) => {
			if (entry.isIntersecting) entry.target.classList.add("visible");
		});
	}, {
		threshold: .1,
		rootMargin: "0px 0px -50px 0px"
	});
	document.querySelectorAll(".fade-up, .text-reveal").forEach((el) => observer.observe(el));
	const form = document.querySelector(".reservation-form");
	if (form) form.addEventListener("submit", (e) => {
		e.preventDefault();
		const btn = form.querySelector("button");
		const originalText = btn.innerText;
		btn.innerText = "Poslano!";
		btn.style.color = "var(--bg-primary)";
		btn.style.borderColor = "var(--accent-gold)";
		btn.classList.add("btn-gold");
		setTimeout(() => {
			btn.innerText = originalText;
			btn.classList.remove("btn-gold");
			form.reset();
		}, 3e3);
	});
	const cookiePopup = document.getElementById("cookiePopup");
	const acceptCookies = document.getElementById("acceptCookies");
	if (cookiePopup && acceptCookies) {
		if (!localStorage.getItem("cookiesAccepted")) setTimeout(() => {
			cookiePopup.classList.add("show");
		}, 2e3);
		acceptCookies.addEventListener("click", () => {
			localStorage.setItem("cookiesAccepted", "true");
			cookiePopup.classList.remove("show");
		});
	}
});
//#endregion
